name: Test FTF script

env:
  praw_client_id: ${{ secrets.PRAW_CLIENT_ID }}
  praw_refresh_token:  ${{secrets.PRAW_REFRESH_TOKEN}}
  praw_user_agent: rcounting_tools/v0.5.1 by u/CutOnBumInBandHere9


on:
  schedule:
    - cron: '45 6 * * 4'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - run: pip install -e .
      - name: FTF
        if: github.event.schedule == '45 6 * * 4'
        run: python3 rcounting/scripts/ftf.py counting_test
