name: Test FTF script

on:
  schedule:
    - cron: '55 12 * * 5'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      praw_refresh_token:  ${{secrets.PRAW_REFRESH_TOKEN}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - run: pip install -e .
      - name: FTF
        if: github.event.schedule == '55 12 * * 5'
        run: python3 rcounting/scripts/ftf.py
